#!/usr/bin/env bash

# DO NOT EDIT. This file generated by tool/generate-help-functions.pl.

set -e

help:all() {
    cat <<'...'
config               config
server-create        server-create
...
}

help:config() {
    cat <<'...'

  Usage: git hub config


  …
...
}

help:server-create() {
    cat <<'...'

  Usage: git hub server-create


  …

= System Dependencies

Ths command requires the following common system tools:

* Bash 3.2 or higher
* Git 1.7.0 or higher
* `curl`

At this stage, it probably will only work on a POSIX system (ie not Windows).
...
}

# vim: set sw=2 lisp:
